version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tripity-server
hooks:
  AfterInstall:
    - location: __bin__/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: __bin__/application-start.sh
      timeout: 30
      runas: root