version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tripity-server-release
permissions:
  - object: /home/ec2-user
    pattern: "tripity-server*"
    owner: ec2-user
    group: ec2-user
    type:
        - directory
hooks:
  BeforeInstall:
    - location: __bin__/before-install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: __bin__/after-install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: __bin__/application-start.sh
      timeout: 30
      runas: ec2-user